### ISSUE TITLE
Feedback & Questions

### ISSUE THREAD

**Issue by RistoPakanen** [RohmSemiconductor/Kionix-IoT-Evaluation-Kit#1]
Please give feedback and ask questions about Kionix IoT Evaluation Kit!

**Comment by RistoPakanen** [comment]
Please start by reading our Users Guide: [Kionix IoT Evaluation Kit Users Guide.pdf](https://github.com/RohmSemiconductor/Kionix-IoT-Evaluation-Kit/blob/master/Kionix%20IoT%20Evaluation%20Kit%20Users%20Guide.pdf)

The Kionix IoT Evaluation Kit provides a powerful and easy to use environment to begin evaluation of Rohm and Kionix products. Multiple hardware options are supported (Kionix Evaluation Kit HW), as well as common, hardware independent sw tools (Kionix Evaluation Kit SW). Kionix Windows Sensor Evaluation Software consists of an easy to use graphical user interface for displaying / recording sensor data and a graphical register map editor which allows the user to see and change the content of control registers. Kionix Multi-OS Evaluation Software, in turn, provides reference implementation for driver sw and also a convenient way to access sensor low level features and versatile data logging functionality.

* Kionix IoT Evaluation Kit Product Page http://www.kionix.com/iot-evaluation-and-development-kit
* Windows users: download and run self-contained [Kionix_IoT_Evaluation_Kit_Setup.exe](https://github.com/RohmSemiconductor/Kionix-IoT-Evaluation-Kit/releases/download/v1.0.5/Kionix_IoT_Evaluation_Kit_Setup.exe)
* Other platform users: clone the repository or download [zipped package](https://github.com/RohmSemiconductor/Kionix-IoT-Evaluation-Kit/archive/master.zip)

**Comment by rakidedigama** [comment]
Hello!

I am using the Kionix Sensor Node with a Windows PC Application. However, I was not able to find source code or Python support /command line tool for establishing a Windows BLE connection to the Kionix Node, except for the GUI that is provided for Windows. 

Is there a way to tweak the connection_setup.py script to be used for a Windows BLE to Kionix Sensor Node connection?

Also,  is there a way to adjust the Sensor streaming time intervals?

Thanks!

**Comment by RistoPakanen** [comment]
Hi!

Windows BLE connection is not yet supported in Kionix Multi-OS Evaluation Software and cannot be tweaked either. However, this functionality is planned to be included in the next release of Kionix IoT Evaluation Kit, which will be published during next month.

Sensor streaming time interval changing is not that simple, but can be changed by using register editor in Kionix Windows Sensor Evaluation Software. Please refer to chapter "5.5.4 Registers - Tab" in [Kionix IoT Evaluation Kit Users Guide.pdf](https://github.com/RohmSemiconductor/Kionix-IoT-Evaluation-Kit/blob/master/Kionix%20IoT%20Evaluation%20Kit%20Users%20Guide.pdf). You need to know which sensor registers must be changed in order to modify ODR. Sensor specifications can be found from the internet. For example: http://www.kionix.com/product/KX122-1037

Our goal is to make ODR changing more simple with Kionix Windows Sensor Evaluation Software in the future. Please note that there are connection limitations with higher ODRs. For example with current Kionix IoT Node firmware, 100Hz is the highest working ODR with BLE connection.

Best Regards,
Risto

**Comment by OdingdongO** [comment]
hi ,can not find the driver file named arduino.inf

I want to use Rohm Multi-Sensor Shield with Arduino UNO, and the “Kionix IoT Evaluation Kit Users Guide” said that
Navigate to and select the driver file named arduino.inf, located in
folder Kionix-IoT-Evaluation-Kit\Kionix-Evaluation-KitFirmware\Arduino-Uno-R3\arduino_usb_drivers.

but there is no folder named Kionix-IoT-Evaluation-Kit\Kionix-Evaluation-KitFirmware\Arduino-Uno-R3\

**Comment by RistoPakanen** [comment]
Hi,

Arduino UNO is not yet supported in Kionix IoT Evaluation Kit. Arduino support is planned for our future releases.

Please refer to the latest [Kionix IoT Evaluation Kit Users Guide.pdf](https://github.com/RohmSemiconductor/Kionix-IoT-Evaluation-Kit/blob/master/Kionix%20IoT%20Evaluation%20Kit%20Users%20Guide.pdf)

Our next release will include Nordic NRF51-DK support. You can use it then with Rohm Multi-Sensor Shield board.

Best Regards,
Risto

**Comment by OdingdongO** [comment]
Hi,

Where can I get an old version that contains arduino.inf? I would like to try to debug ROHM_SensorPlatform_Multi-Sensor-Shield and arduino with Kionix-Multi-OS-Evaluation-Software

is it possible?
thank you

**Comment by RistoPakanen** [comment]
Hi,

Arduino.inf as well as other files needed for generic Arduino support is included in Arduino IDE installer.

Please note that Arduino is not yet officially supported in “Kionix-Multi-OS-Evaluation-Software”.
You may consider to use Nordic nRF51-DK which will be supported soon or use Arduino examples in
https://github.com/ROHMUSDC/ROHM_SensorPlatform_Multi-Sensor-Shield/tree/master/Platform%20Code

Best Regards,
Risto

**Comment by OdingdongO** [comment]
Does Nordic nRF51-DK and ROHM_SensorPlatform_Multi-Sensor-Shield support stream mode?

thank you

**Comment by RistoPakanen** [comment]
Hi,

Yes, it does. Same firmware is used in both Kionix IoT Sensor Node and Nordic nRF51-DK. Also same connections are supported, both USB and Bluetooth.

Best Regards,
Risto

**Comment by rakidedigama** [comment]
Hi, 

Is the Source for the Kionix IoT Node's BLE application software in the public domain? 

Thanks

**Comment by MiLaak** [comment]
Hi,

We provide only binaries for Kionix IoT Node's firmware.

Kind Regards,
Mika
