### ISSUE TITLE
can not find the driver file named arduino.inf

### ISSUE THREAD

**Issue by OdingdongO** [RohmSemiconductor/Kionix-IoT-Evaluation-Kit#2]
I want to use Rohm Multi-Sensor Shield with Arduino UNO, and the “Kionix IoT Evaluation Kit Users Guide” said that 
Navigate to and select the driver file named arduino.inf, located in
folder Kionix-IoT-Evaluation-Kit\Kionix-Evaluation-KitFirmware\Arduino-Uno-R3\arduino_usb_drivers.

but there is no folder named  Kionix-IoT-Evaluation-Kit\Kionix-Evaluation-KitFirmware\Arduino-Uno-R3\

**Comment by RistoPakanen** [comment]
Hi,

Arduino UNO is not yet supported in Kionix IoT Evaluation Kit. Arduino support is planned for our future releases.

Please refer to the latest [Kionix IoT Evaluation Kit Users Guide.pdf](https://github.com/RohmSemiconductor/Kionix-IoT-Evaluation-Kit/blob/master/Kionix%20IoT%20Evaluation%20Kit%20Users%20Guide.pdf)

Our next release will include Nordic NRF51-DK support. You can use it then with Rohm Multi-Sensor Shield board.

Best Regards,
Risto

**Comment by RistoPakanen** [comment]
Hi,

Arduino.inf as well as other files needed for generic Arduino support is included in Arduino IDE installer.

Please note that Arduino is not yet officially supported in “Kionix-Multi-OS-Evaluation-Software”.
You may consider to use Nordic nRF51-DK which will be supported soon or use Arduino examples in 
https://github.com/ROHMUSDC/ROHM_SensorPlatform_Multi-Sensor-Shield/tree/master/Platform%20Code

Best Regards,
Risto
