### ISSUE TITLE
Error while trying to use on ubuntu 16.04.2

### ISSUE THREAD

**Issue by shamazharikh** [RohmSemiconductor/Kionix-IoT-Evaluation-Kit#3]
While trying to use this repo on ubuntu 16.04.2, i ran into the following error attached.
[error_log.txt](https://github.com/RohmSemiconductor/Kionix-IoT-Evaluation-Kit/files/1026635/error_log.txt)
It says i need to install pywin32, but that is only available for a windows system, and I'm not even using a windows system. Please instruct on how to use your code on an ubuntu machine.

**Comment by MiLaak** [comment]
Hello Shamazharikh,

Sorry to hear that you have faced problems with evaluation kit SW. The reason for the error message is that port auto discovery is not supported in Linux. Fix is to define manually correct connection to settings.cfg.
By default the configuration is "com_port=auto" which works on Windows OS. 
https://github.com/RohmSemiconductor/Kionix-IoT-Evaluation-Kit/blob/master/Kionix-Multi-OS-Evaluation-Software/settings.cfg#L94 

Linux configuration looks for example like this:
com_port = /dev/ttyUSB0

Proper port in Linux could be found for example with dmesg command.

Best Regards,
Mika
