### ISSUE TITLE
Reloading Select Set of Registers

### ISSUE THREAD

**Issue by SensorsGuy** [RohmSemiconductor/Kionix-IoT-Evaluation-Kit#4]
The Select Set is very useful to only show a smaller set of registers.  When developing a "set" I find it takes a number of iterations to choose the right set of registers for inclusion in a "set".  If I edit the text file listing the set of registers, I seem to need to close down the GUI and re-open and re-connect in order to re-load the modified set of registers.  It would be good if simply selecting the drop down re-scanned the directory and then selecting a "set" re-loaded the file (it seems the files are loaded at startup and not reloaded when they are selected so changes are not seen unless the GUI is re-started)

**Comment by RistoPakanen** [comment]
Fixed in https://github.com/RohmSemiconductor/Kionix-IoT-Evaluation-Kit/releases/tag/v1.3.1_Pre
- now the register set is reloaded when you reload the register xml file
